sonar.projectKey=research-projects-all_django-oscar
sonar.organization=research-projects-all

sonar.sources=src
sonar.tests=tests

sonar.exclusions=tests/**,**/build-wrapper-dump.json
sonar.coverage.exclusions=**/migrations/**,**/oscar/test/**
sonar.python.version=3.11
